USE BasketballDB
GO

CREATE TABLE Positions(
	PositionID INT IDENTITY(1,1) PRIMARY KEY,
	PositionName NVARCHAR(50) NOT NULL
);

CREATE TABLE Teams(
	TeamGuid UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	TeamName NVARCHAR(100) NOT NULL,
	Budget DECIMAL(18, 2) NOT NULL,
	FoundedYear INT NOT NULL
);

CREATE TABLE Players(
	PlayerID INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastNmae NVARCHAR(50) NOT NULL,
	BirthDate DATETIME2 NOT NULL,
	IsActive BIT DEFAULT 1,
	TeamGuid UNIQUEIDENTIFIER NOT NULL,
	PositionID INT NOT NULL,

	CONSTRAINT FK_Players_Teams FOREIGN KEY(TeamGuid) REFERENCES Teams(TeamGuid) ON DELETE CASCADE,
	CONSTRAINT FK_Players_Position FOREIGN KEY(PositionID) REFERENCES Positions(PositionID)
);

CREATE TABLE Matches(
	MatchID INT IDENTITY(1,1) PRIMARY KEY,
	MatchDate DATETIME2 NOT NULL,
	ArenaName NVARCHAR(150) NOT NULL,
	HomeTeamGuid UNIQUEIDENTIFIER NOT NULL,
	AwayTeamGuid UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Matches_HomeTeam FOREIGN KEY(HomeTeamGuid) REFERENCES Teams(TeamGuid),
	CONSTRAINT FK_Matches_AwayTeam FOREIGN KEY(AwayTeamGuid) REFERENCES Teams(TeamGuid)
);

CREATE TABLE PlayerMatchStats(
	PlayerID INT NOT NULL,
	MatchID INT NOT NULL,
	PointsScored INT DEFAULT 0,
	FoulsCount INT DEFAULT 0,

	PRIMARY KEY (PlayerID, MatchID),

	CONSTRAINT FK_Stats_Players FOREIGN KEY(PlayerID) REFERENCES Players(PlayerID) ON DELETE CASCADE,
	CONSTRAINT FK_Stats_Matchs FOREIGN KEY(MatchID) REFERENCES Matches(MatchID) ON DELETE CASCADE
);
GO

CREATE UNIQUE INDEX UIX_Teams_TeamName ON Teams(TeamName);
GO	